workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_play # <-- (Includes GCLOUD_SERVICE_ACCOUNT_CREDENTIALS <-- Put your google-services.json here)
      vars:
        PACKAGE_NAME: "ch.mathieubroillet.djiffchack"
      java: 17
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android Debug APK
        script: |
          ./gradlew assembleDebug
      - name: Build Android Release APK
        script: |
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
      - app/build/outputs/**/mapping.txt
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: false
          failure: true
