workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "ch.mathieubroillet.djiffchack"
      java: 17
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android Debug APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/mapping.txt
    publishing:
      email:
        recipients:
          - your-email@example.com # Replace with your actual email address
        notify:
          success: false
          failure: true
